# Generated by Django 5.2.1 on 2025-05-23 15:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_oficina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='data_criacao_os',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='valor_total_os',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
