# Generated by Django 5.2.1 on 2025-05-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_oficina', '0002_remove_ordemdeservico_data_criacao_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='numero_os',
            field=models.CharField(blank=True, editable=False, help_text='Número único da Ordem de Serviço (gerado automaticamente)', max_length=50, unique=True),
        ),
    ]
